apiVersion: v1
kind: Service
metadata:
  name: {{ include "custom.fullname" . }}
  labels:
    {{- include "custom.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }} # Prende 'ClusterIP' dal values.yaml
  ports:
    - port: {{ .Values.service.port }} # Prende '5000' dal values.yaml
      targetPort: 5000             # La porta interna del container Flask
      protocol: TCP
      name: http
      # nodePort rimosso perch√© proibito in ClusterIP
  selector:
    {{- include "custom.selectorLabels" . | nindent 4 }}